# Generated by scripts/release.sh for Sesh 0.7.1.
class Sesh < Formula
  desc "Host daemon and CLI for Sesh, the client for coding agents on your machines"
  homepage "https://github.com/hipstersmoothie/sesh-app"
  version "0.7.1"

  on_macos do
    url "https://sesh.codes/releases/v0.7.1/sesh-0.7.1-macos-universal.tar.gz"
    sha256 "223dd07a2ce989fda81d065b0278e14d2aa922406802db5d46347b8bd2e3521d"
  end
  on_linux do
    on_intel do
      url "https://sesh.codes/releases/v0.7.1/sesh-0.7.1-linux-x86_64.tar.gz"
      sha256 "564cc52fdb117b148ff081fa60ed2503e517dee883983c05b44a85ee3b3ce348"
    end
    on_arm do
      url "https://sesh.codes/releases/v0.7.1/sesh-0.7.1-linux-aarch64.tar.gz"
      sha256 "92e153522c01c784b978790376c12782c01a93025c31ed9d4632854dcdd47581"
    end
  end

  def install
    bin.install "seshd", "sesh"
  end

  service do
    run [opt_bin/"seshd"]
    keep_alive true
    log_path var/"log/seshd.log"
    error_log_path var/"log/seshd.log"
  end

  def caveats
    <<~EOS
      After `brew services start sesh/tap/sesh`, run `sesh pair` to pair your other devices:
      they reach this machine by its ID, from any network.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/seshd --version")
  end
end
