# Generated by scripts/release.sh for Sesh 0.7.2.
class Sesh < Formula
  desc "Host daemon and CLI for Sesh, the client for coding agents on your machines"
  homepage "https://github.com/hipstersmoothie/sesh-app"
  version "0.7.2"

  on_macos do
    url "https://sesh.codes/releases/v0.7.2/sesh-0.7.2-macos-universal.tar.gz"
    sha256 "a368258387bd39a192860aef365f27f8d204eac59148bae980d2b486274edb75"
  end
  on_linux do
    on_intel do
      url "https://sesh.codes/releases/v0.7.2/sesh-0.7.2-linux-x86_64.tar.gz"
      sha256 "84069a2e6a89c376f8012b69697f4f71a0b6935fa759eeb0e0fded07d164c858"
    end
    on_arm do
      url "https://sesh.codes/releases/v0.7.2/sesh-0.7.2-linux-aarch64.tar.gz"
      sha256 "804d71e2391b218fd17b1136b4f3f78e7bcf6d9c60e2ad3a124532a6ebf79846"
    end
  end

  def install
    bin.install "seshd", "sesh"
  end

  service do
    run [opt_bin/"seshd"]
    keep_alive true
    log_path var/"log/seshd.log"
    error_log_path var/"log/seshd.log"
  end

  def caveats
    <<~EOS
      After `brew services start sesh/tap/sesh`, run `sesh pair` to pair your other devices:
      they reach this machine by its ID, from any network.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/seshd --version")
  end
end
