# Generated by scripts/release.sh for Sesh 0.7.5.
class Sesh < Formula
  desc "Host daemon and CLI for Sesh, the client for coding agents on your machines"
  homepage "https://github.com/hipstersmoothie/sesh-app"
  version "0.7.5"

  on_macos do
    url "https://sesh.codes/releases/v0.7.5/sesh-0.7.5-macos-universal.tar.gz"
    sha256 "b9fee938638edb85caa65d7922acea1d566d54f411e85f893d3dc988484ef7b8"
  end
  on_linux do
    on_intel do
      url "https://sesh.codes/releases/v0.7.5/sesh-0.7.5-linux-x86_64.tar.gz"
      sha256 "acb9b85d30dd7e667f240620e56b1621a8faa16ce47b636c5c4f2161e5fd6f84"
    end
    on_arm do
      url "https://sesh.codes/releases/v0.7.5/sesh-0.7.5-linux-aarch64.tar.gz"
      sha256 "11a0c0bb33ecca1d5cf490a33e3444b2fe13b0b965d4d847be74aeb107f24c05"
    end
  end

  def install
    bin.install "seshd", "sesh"
  end

  service do
    run [opt_bin/"seshd"]
    keep_alive true
    log_path var/"log/seshd.log"
    error_log_path var/"log/seshd.log"
  end

  def caveats
    <<~EOS
      After `brew services start sesh/tap/sesh`, run `sesh pair` to pair your other devices:
      they reach this machine by its ID, from any network.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/seshd --version")
  end
end
